default_language_version:
  python: python3

exclude: ^(.cruft.json|.copier-answers.yml|performance_scripts/data\.py|performance_scripts/csvs/)$

default_stages: [pre-commit, pre-push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        exclude: \.(json)$
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
        exclude: ^tests/cases\.py$|.*\.json$
      - id: forbid-submodules
      - id: no-commit-to-branch
        args: ['--pattern', '[^a-zA-Z0-9_\/-]']
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.14.8"
    hooks:
      - id: ruff-check
        exclude: (docs/)
      - id: ruff-format
        exclude: (docs/)
        args: [--check]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.8
    hooks:
      - id: uv-lock

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: "v21.1.8"
    hooks:
      - id: clang-format
        types_or: [c++, c, cuda]
        verbose: true
        args: [--verbose]

  - repo: https://github.com/BlankSpruce/gersemi
    rev: "0.22.1"
    hooks:
    - id: gersemi
      exclude: ^(cmake/CPM\.cmake$)

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: "v1.5.6"
    hooks:
      - id: insert-license
        name: check Python license header
        types: [python]
        args:
          - --license-filepath
          - .github/license-header.txt
          - --comment-style
          - "#"
      - id: insert-license
        name: check C++ license header
        files: \.(cpp|h|hpp|c|cc|cxx|cuda|cu|cuh|inl)(\.in)?$
        exclude: (^|/)(CMakeLists\.txt|.*\.cmake)$
        args:
          - --license-filepath
          - .github/license-header.txt
          - --comment-style
          - "//"

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: "0.33.3"
    hooks:
      - id: check-dependabot
      - id: check-github-workflows
      - id: check-github-actions
