sonar.projectKey=Algorithmiq_monoprop
sonar.organization=algorithmiq

sonar.projectName=monoprop
sonar.sources=cpp/monoprop,cpp/include
sonar.exclusions=benches/*,src/monoprop/_version.py,src/monoprop/_dispatch.py
sonar.test.exclusions=tests/data/**
sonar.sourceEncoding=UTF-8
sonar.tests=tests
sonar.verbose=true
sonar.python.version=3.11,3.12,3.13,3.14
sonar.lang.patterns.c=**/*.c
sonar.lang.patterns.cpp=**/*.cpp,**/*.h,**/*.hpp,**/*.inl
