#!/usr/bin/env python3
# Copyright 2026 Algorithmiq
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Check a Python package's public API for breaking changes, via griffe.

Calls `griffe.find_breaking_changes` directly rather than going through the
`griffe check` CLI (`griffecli`), for two reasons:

- This repo carries non-release tags (`archive/...`, `tool/...`, `arm/...`)
  created after the latest release tag. The CLI's default "latest tag" is
  `git tag -l --sort=-creatordate`, which picks the most *recently created*
  tag -- one of those -- rather than the latest release. `git describe`
  instead walks commit ancestry from HEAD, which is what a "latest version to
  diff against" should mean, so that is what `_latest_tag` below uses.
- The CLI has no way to exclude a known-noisy path from the report; filtering
  `find_breaking_changes`'s output is straightforward.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys

import griffe

# `_version.py` is regenerated by setuptools-scm at build time
# (`tool.setuptools_scm.write_to` in pyproject.toml); its values always differ
# between two checkouts and are never a real API break.
_EXCLUDED_PATHS = frozenset(
    {
        "monoprop._version.version",
        "monoprop._version.version_tuple",
    }
)


def _latest_tag() -> str:
    """The most recent tag reachable from HEAD, by commit ancestry."""
    git = shutil.which("git")
    if git is None:
        raise RuntimeError("git not found on PATH")
    return subprocess.run(  # noqa: S603 -- fixed argv, no untrusted input
        [git, "describe", "--tags", "--abbrev=0"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()


def main() -> int:
    """Report breaking changes between two refs of a package's public API."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "module", nargs="?", default="monoprop", help="The module to check"
    )
    parser.add_argument(
        "-a",
        "--against",
        help="Older git ref to check against (default: the latest tag reachable from HEAD)",
    )
    parser.add_argument(
        "-b",
        "--base-ref",
        help="Newer git ref to check (default: the current working tree)",
    )
    parser.add_argument(
        "-s", "--search", default="src", help="Search path for the package sources"
    )
    parser.add_argument(
        "-f",
        "--format",
        default="verbose",
        choices=[style.value for style in griffe.ExplanationStyle],
        help="Explanation style",
    )
    args = parser.parse_args()

    against = args.against or _latest_tag()
    search_paths = [args.search]

    old = griffe.load_git(
        args.module, ref=against, search_paths=search_paths, resolve_aliases=True
    )
    new = (
        griffe.load_git(
            args.module,
            ref=args.base_ref,
            search_paths=search_paths,
            resolve_aliases=True,
        )
        if args.base_ref
        else griffe.load(args.module, search_paths=search_paths, resolve_aliases=True)
    )

    all_breakages = list(griffe.find_breaking_changes(old, new))
    breakages = [b for b in all_breakages if b.obj.path not in _EXCLUDED_PATHS]
    excluded = len(all_breakages) - len(breakages)

    style = griffe.ExplanationStyle(args.format)
    for breakage in breakages:
        print(breakage.explain(style=style), file=sys.stderr)

    base_label = args.base_ref or "the working tree"
    summary = f"\nmonoprop API check: {against} -> {base_label}: {len(breakages)} breaking change(s)"
    if excluded:
        summary += f" ({excluded} excluded)"
    print(summary + ".", file=sys.stderr)

    return 1 if breakages else 0


if __name__ == "__main__":
    raise SystemExit(main())
