# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2024.08.19
_src_path: gh:scientific-python/cookie
backend: skbuild
email: roberto@algorithmiq.fi
full_name: Roberto Di Remigio Eikås
license: Apache
org: Algorithmiq
project_name: monoprop
project_short_description: A great package.
url: https://github.com/Algorithmiq/monoprop
vcs: true
