# Copyright 2026 Algorithmiq
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ruff: noqa: INP001

"""Normalize machine flags from ``clang -###`` output.

Reads the command output from stdin and extracts a stable, space-separated list
of machine-relevant flags. For AppleClang we keep only ``-march=``, ``-mcpu=``,
``-mtune=``, ``-target-cpu=``, and ``-target-feature=`` forms.
"""

from __future__ import annotations

import shlex
import sys

_ALLOWED_PREFIXES = (
    "-march=",
    "-mcpu=",
    "-mtune=",
    "-target-cpu=",
    "-target-feature=",
)


def _append_unique(entries: list[str], seen: set[str], value: str) -> None:
    """Append a flag only once, preserving first-seen order."""
    if value not in seen:
        seen.add(value)
        entries.append(value)


def _normalize_pair_flag(flag: str, value: str) -> str:
    """Normalize pair-style machine flags into ``-key=value`` form."""
    return f"{flag}={value}"


def clean_target_help(text: str) -> str:
    """Normalize ``clang -###`` output into a single machine-flag string.

    Args:
        text: The full output generated by ``clang -###``.

    Returns:
        A space-separated string containing unique normalized machine flags in
        first-seen order.
    """
    tokens = shlex.split(text.replace("\n", " "))
    entries: list[str] = []
    seen: set[str] = set()
    pair_flags = {"-march", "-mcpu", "-mtune", "-target-cpu", "-target-feature"}

    idx = 0
    while idx < len(tokens):
        tok = tokens[idx]

        if tok.startswith(_ALLOWED_PREFIXES):
            _append_unique(entries, seen, tok)
        elif tok in pair_flags and idx + 1 < len(tokens):
            normalized = _normalize_pair_flag(tok, tokens[idx + 1])
            _append_unique(entries, seen, normalized)
            idx += 1

        idx += 1

    return " ".join(entries)


def main() -> None:
    """Read stdin and print normalized machine flags."""
    sys.stdout.write(clean_target_help(sys.stdin.read()) + "\n")


if __name__ == "__main__":
    main()
