[project]
name = "monoprop-benchmarks"
version = "0.1.0"
description = "Standalone benchmark scripts for monoprop"
requires-python = "==3.12.12"
dependencies = [
    "monoprop",
    "pennylane",
    "qiskit",
    "tqdm",
    "ppvm",
    "pauli-prop",
    "cuquantum-python-cu12",
]

[tool.uv]
python-preference = "only-managed"

[tool.uv.extra-build-variables.ppvm]
RUSTFLAGS = "-C target-feature=+aes,+neon"

[tool.ruff.lint.per-file-ignores]
"**/*.py" = ["INP001"]

[tool.uv.sources]
monoprop = { path = ".." }
ppvm = { git = "https://github.com/QuEraComputing/ppvm.git", subdirectory = "ppvm-python" }
