name: Approve and enable automerge for all automated PRs
on: pull_request

jobs:
  handle-automated-prs:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    # only run if the PR is created by dependabot or github actions bot
    if: >
      github.repository == 'Algorithmiq/monoprop' &&
      (
        github.event.pull_request.user.login == 'dependabot[bot]' ||
        github.event.pull_request.user.login == 'github-actions[bot]'
      )
    steps:
      - name: Dependabot metadata
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        id: metadata
        uses: dependabot/fetch-metadata@v3
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Approve a PR
        run: |
            # approve the PR
            gh pr review --approve "$PR_URL" --body "Automated approval for an automated PR"
            # enable automerge
            gh pr merge --squash --auto "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          # The PAT needs the following permissions:
          # - Pull Requests: Read & Write (to approve)
          # - Contents: Read & Write (to enable auto merge)
          GH_TOKEN: ${{secrets.APPROVE_AUTO_MERGE_PAT}}
